### ISSUE TITLE
./cdmiservice error

### ISSUE THREAD

**Issue by taraninomula** [fraunhoferfokus/open-content-decryption-module-cdmi#8]
when i am executing belowe it shows something like below error. 
/cdmiservice 
Cannot register service: RPC: Unable to receive; errno = Connection refused
unable to register (OPEN_CDM, OPEN_CDM_EME_5, udp).

**Comment by squapp** [comment]
please check if this helps: https://stackoverflow.com/questions/10448696/error-on-trying-to-run-a-simple-rpc-program

**Comment by taraninomula** [comment]
yes, i installed rpcbind and after that ./cdmiservice also working fine but what will be the output when i am executing ./cdmiservice.

**Comment by squapp** [comment]
logs should be shown once messages are sent to the cdmiservice. Apart from that there will be no output

**Comment by taraninomula** [comment]
@squapp Thank you
